/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p/$token'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppPackagesIndexRouteImport } from './routes/_app/packages/index'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppCandidatesIndexRouteImport } from './routes/_app/candidates/index'
import { Route as AppAcademyIndexRouteImport } from './routes/_app/academy/index'
import { Route as ApiPublicTrackBehaviorRouteImport } from './routes/api/public/track-behavior'
import { Route as ApiPublicNotifyRhRouteImport } from './routes/api/public/notify-rh'
import { Route as ApiPublicComputeEngagementRouteImport } from './routes/api/public/compute-engagement'
import { Route as AppPackagesNewRouteImport } from './routes/_app/packages/new'
import { Route as AppJobsNewRouteImport } from './routes/_app/jobs/new'
import { Route as AppJobsIdRouteImport } from './routes/_app/jobs/$id'
import { Route as AppCandidatesIdRouteImport } from './routes/_app/candidates/$id'
import { Route as AppAcademyRsuRouteImport } from './routes/_app/academy/rsu'
import { Route as AppPackagesIdIndexRouteImport } from './routes/_app/packages/$id/index'
import { Route as ApiPublicHooksRunRemindersRouteImport } from './routes/api/public/hooks/run-reminders'
import { Route as ApiPublicHooksDeadlineNotifierRouteImport } from './routes/api/public/hooks/deadline-notifier'
import { Route as AppPackagesIdEditRouteImport } from './routes/_app/packages/$id/edit'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesIndexRoute = AppPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyIndexRoute = AppAcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTrackBehaviorRoute = ApiPublicTrackBehaviorRouteImport.update({
  id: '/api/public/track-behavior',
  path: '/api/public/track-behavior',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyRhRoute = ApiPublicNotifyRhRouteImport.update({
  id: '/api/public/notify-rh',
  path: '/api/public/notify-rh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicComputeEngagementRoute =
  ApiPublicComputeEngagementRouteImport.update({
    id: '/api/public/compute-engagement',
    path: '/api/public/compute-engagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPackagesNewRoute = AppPackagesNewRouteImport.update({
  id: '/packages/new',
  path: '/packages/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyRsuRoute = AppAcademyRsuRouteImport.update({
  id: '/academy/rsu',
  path: '/academy/rsu',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesIdIndexRoute = AppPackagesIdIndexRouteImport.update({
  id: '/packages/$id/',
  path: '/packages/$id/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksRunRemindersRoute =
  ApiPublicHooksRunRemindersRouteImport.update({
    id: '/api/public/hooks/run-reminders',
    path: '/api/public/hooks/run-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeadlineNotifierRoute =
  ApiPublicHooksDeadlineNotifierRouteImport.update({
    id: '/api/public/hooks/deadline-notifier',
    path: '/api/public/hooks/deadline-notifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPackagesIdEditRoute = AppPackagesIdEditRouteImport.update({
  id: '/packages/$id/edit',
  path: '/packages/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/p/$token': typeof PTokenRoute
  '/academy/rsu': typeof AppAcademyRsuRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/packages/new': typeof AppPackagesNewRoute
  '/api/public/compute-engagement': typeof ApiPublicComputeEngagementRoute
  '/api/public/notify-rh': typeof ApiPublicNotifyRhRoute
  '/api/public/track-behavior': typeof ApiPublicTrackBehaviorRoute
  '/academy/': typeof AppAcademyIndexRoute
  '/candidates/': typeof AppCandidatesIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/packages/': typeof AppPackagesIndexRoute
  '/packages/$id/edit': typeof AppPackagesIdEditRoute
  '/api/public/hooks/deadline-notifier': typeof ApiPublicHooksDeadlineNotifierRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/packages/$id/': typeof AppPackagesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/p/$token': typeof PTokenRoute
  '/academy/rsu': typeof AppAcademyRsuRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/packages/new': typeof AppPackagesNewRoute
  '/api/public/compute-engagement': typeof ApiPublicComputeEngagementRoute
  '/api/public/notify-rh': typeof ApiPublicNotifyRhRoute
  '/api/public/track-behavior': typeof ApiPublicTrackBehaviorRoute
  '/academy': typeof AppAcademyIndexRoute
  '/candidates': typeof AppCandidatesIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/packages': typeof AppPackagesIndexRoute
  '/packages/$id/edit': typeof AppPackagesIdEditRoute
  '/api/public/hooks/deadline-notifier': typeof ApiPublicHooksDeadlineNotifierRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/packages/$id': typeof AppPackagesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/p/$token': typeof PTokenRoute
  '/_app/academy/rsu': typeof AppAcademyRsuRoute
  '/_app/candidates/$id': typeof AppCandidatesIdRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/packages/new': typeof AppPackagesNewRoute
  '/api/public/compute-engagement': typeof ApiPublicComputeEngagementRoute
  '/api/public/notify-rh': typeof ApiPublicNotifyRhRoute
  '/api/public/track-behavior': typeof ApiPublicTrackBehaviorRoute
  '/_app/academy/': typeof AppAcademyIndexRoute
  '/_app/candidates/': typeof AppCandidatesIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/packages/': typeof AppPackagesIndexRoute
  '/_app/packages/$id/edit': typeof AppPackagesIdEditRoute
  '/api/public/hooks/deadline-notifier': typeof ApiPublicHooksDeadlineNotifierRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
  '/_app/packages/$id/': typeof AppPackagesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/welcome'
    | '/alerts'
    | '/dashboard'
    | '/settings'
    | '/p/$token'
    | '/academy/rsu'
    | '/candidates/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/packages/new'
    | '/api/public/compute-engagement'
    | '/api/public/notify-rh'
    | '/api/public/track-behavior'
    | '/academy/'
    | '/candidates/'
    | '/jobs/'
    | '/packages/'
    | '/packages/$id/edit'
    | '/api/public/hooks/deadline-notifier'
    | '/api/public/hooks/run-reminders'
    | '/packages/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/welcome'
    | '/alerts'
    | '/dashboard'
    | '/settings'
    | '/p/$token'
    | '/academy/rsu'
    | '/candidates/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/packages/new'
    | '/api/public/compute-engagement'
    | '/api/public/notify-rh'
    | '/api/public/track-behavior'
    | '/academy'
    | '/candidates'
    | '/jobs'
    | '/packages'
    | '/packages/$id/edit'
    | '/api/public/hooks/deadline-notifier'
    | '/api/public/hooks/run-reminders'
    | '/packages/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/welcome'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/p/$token'
    | '/_app/academy/rsu'
    | '/_app/candidates/$id'
    | '/_app/jobs/$id'
    | '/_app/jobs/new'
    | '/_app/packages/new'
    | '/api/public/compute-engagement'
    | '/api/public/notify-rh'
    | '/api/public/track-behavior'
    | '/_app/academy/'
    | '/_app/candidates/'
    | '/_app/jobs/'
    | '/_app/packages/'
    | '/_app/packages/$id/edit'
    | '/api/public/hooks/deadline-notifier'
    | '/api/public/hooks/run-reminders'
    | '/_app/packages/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WelcomeRoute: typeof WelcomeRoute
  PTokenRoute: typeof PTokenRoute
  ApiPublicComputeEngagementRoute: typeof ApiPublicComputeEngagementRoute
  ApiPublicNotifyRhRoute: typeof ApiPublicNotifyRhRoute
  ApiPublicTrackBehaviorRoute: typeof ApiPublicTrackBehaviorRoute
  ApiPublicHooksDeadlineNotifierRoute: typeof ApiPublicHooksDeadlineNotifierRoute
  ApiPublicHooksRunRemindersRoute: typeof ApiPublicHooksRunRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/': {
      id: '/_app/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof AppPackagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/': {
      id: '/_app/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academy/': {
      id: '/_app/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AppAcademyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/track-behavior': {
      id: '/api/public/track-behavior'
      path: '/api/public/track-behavior'
      fullPath: '/api/public/track-behavior'
      preLoaderRoute: typeof ApiPublicTrackBehaviorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-rh': {
      id: '/api/public/notify-rh'
      path: '/api/public/notify-rh'
      fullPath: '/api/public/notify-rh'
      preLoaderRoute: typeof ApiPublicNotifyRhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/compute-engagement': {
      id: '/api/public/compute-engagement'
      path: '/api/public/compute-engagement'
      fullPath: '/api/public/compute-engagement'
      preLoaderRoute: typeof ApiPublicComputeEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/packages/new': {
      id: '/_app/packages/new'
      path: '/packages/new'
      fullPath: '/packages/new'
      preLoaderRoute: typeof AppPackagesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/$id': {
      id: '/_app/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academy/rsu': {
      id: '/_app/academy/rsu'
      path: '/academy/rsu'
      fullPath: '/academy/rsu'
      preLoaderRoute: typeof AppAcademyRsuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/$id/': {
      id: '/_app/packages/$id/'
      path: '/packages/$id'
      fullPath: '/packages/$id/'
      preLoaderRoute: typeof AppPackagesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/run-reminders': {
      id: '/api/public/hooks/run-reminders'
      path: '/api/public/hooks/run-reminders'
      fullPath: '/api/public/hooks/run-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deadline-notifier': {
      id: '/api/public/hooks/deadline-notifier'
      path: '/api/public/hooks/deadline-notifier'
      fullPath: '/api/public/hooks/deadline-notifier'
      preLoaderRoute: typeof ApiPublicHooksDeadlineNotifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/packages/$id/edit': {
      id: '/_app/packages/$id/edit'
      path: '/packages/$id/edit'
      fullPath: '/packages/$id/edit'
      preLoaderRoute: typeof AppPackagesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAcademyRsuRoute: typeof AppAcademyRsuRoute
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppPackagesNewRoute: typeof AppPackagesNewRoute
  AppAcademyIndexRoute: typeof AppAcademyIndexRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppPackagesIndexRoute: typeof AppPackagesIndexRoute
  AppPackagesIdEditRoute: typeof AppPackagesIdEditRoute
  AppPackagesIdIndexRoute: typeof AppPackagesIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAcademyRsuRoute: AppAcademyRsuRoute,
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppJobsNewRoute: AppJobsNewRoute,
  AppPackagesNewRoute: AppPackagesNewRoute,
  AppAcademyIndexRoute: AppAcademyIndexRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppPackagesIndexRoute: AppPackagesIndexRoute,
  AppPackagesIdEditRoute: AppPackagesIdEditRoute,
  AppPackagesIdIndexRoute: AppPackagesIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WelcomeRoute: WelcomeRoute,
  PTokenRoute: PTokenRoute,
  ApiPublicComputeEngagementRoute: ApiPublicComputeEngagementRoute,
  ApiPublicNotifyRhRoute: ApiPublicNotifyRhRoute,
  ApiPublicTrackBehaviorRoute: ApiPublicTrackBehaviorRoute,
  ApiPublicHooksDeadlineNotifierRoute: ApiPublicHooksDeadlineNotifierRoute,
  ApiPublicHooksRunRemindersRoute: ApiPublicHooksRunRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
