ALTER TABLE public.packages
  ADD COLUMN IF NOT EXISTS job_title          text,
  ADD COLUMN IF NOT EXISTS job_family         text,
  ADD COLUMN IF NOT EXISTS seniority          text,
  ADD COLUMN IF NOT EXISTS location           text,
  ADD COLUMN IF NOT EXISTS start_date_specific date,
  ADD COLUMN IF NOT EXISTS hiring_manager     text,
  ADD COLUMN IF NOT EXISTS why_open           text,
  ADD COLUMN IF NOT EXISTS fixed_salary       integer,
  ADD COLUMN IF NOT EXISTS salary_range_min   integer,
  ADD COLUMN IF NOT EXISTS salary_range_max   integer,
  ADD COLUMN IF NOT EXISTS salary_show_range  boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS salary_negotiable  boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS variable_enabled   boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS variable_max       integer,
  ADD COLUMN IF NOT EXISTS variable_criteria  text,
  ADD COLUMN IF NOT EXISTS variable_frequency text,
  ADD COLUMN IF NOT EXISTS variable_guaranteed_months integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS signing_bonus_amount   integer,
  ADD COLUMN IF NOT EXISTS signing_bonus_clawback_months integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS equity_type        text,
  ADD COLUMN IF NOT EXISTS equity_quantity    integer,
  ADD COLUMN IF NOT EXISTS equity_strike_price numeric(10,4),
  ADD COLUMN IF NOT EXISTS equity_vesting_years integer DEFAULT 4,
  ADD COLUMN IF NOT EXISTS equity_cliff_months  integer DEFAULT 12,
  ADD COLUMN IF NOT EXISTS equity_acceleration  boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS equity_valuation     bigint,
  ADD COLUMN IF NOT EXISTS equity_notes         text,
  ADD COLUMN IF NOT EXISTS remote_work_override boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS remote_work_days_specific integer,
  ADD COLUMN IF NOT EXISTS equipment_laptop   text,
  ADD COLUMN IF NOT EXISTS equipment_budget   integer,
  ADD COLUMN IF NOT EXISTS training_budget_specific integer,
  ADD COLUMN IF NOT EXISTS training_details   text,
  ADD COLUMN IF NOT EXISTS probation_months   integer DEFAULT 3,
  ADD COLUMN IF NOT EXISTS probation_objectives text,
  ADD COLUMN IF NOT EXISTS career_path        text,
  ADD COLUMN IF NOT EXISTS non_compete_enabled    boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS non_compete_months     integer,
  ADD COLUMN IF NOT EXISTS non_compete_compensation_pct integer,
  ADD COLUMN IF NOT EXISTS mobility_clause        boolean DEFAULT false;